# Generated by Django 3.0.1 on 2020-06-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='gallery')),
                ('pic1', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic2', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic3', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic4', models.ImageField(default='none', null=True, upload_to='gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='gallery')),
                ('pic1', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic2', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic3', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic4', models.ImageField(default='none', null=True, upload_to='gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='gallery')),
                ('pic1', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic2', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic3', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic4', models.ImageField(default='none', null=True, upload_to='gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='gallery')),
                ('pic1', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic2', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic3', models.ImageField(default='none', null=True, upload_to='gallery')),
                ('pic4', models.ImageField(default='none', null=True, upload_to='gallery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
