# Generated by Django 3.0.1 on 2020-06-18 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_car_motorcycle_suv_truck'),
    ]

    operations = [
    ]
