# Generated by Django 3.0.1 on 2020-06-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0004_auto_20200618_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pic',
            field=models.ImageField(default='gallery/error.png', upload_to='gallery'),
        ),
    ]
