# Generated by Django 3.0.1 on 2020-06-19 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0010_auto_20200618_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pic',
            field=models.ImageField(default='gallery/error.png', upload_to='gallery'),
        ),
        migrations.DeleteModel(
            name='CarPic',
        ),
    ]
