# Generated by Django 3.0.1 on 2020-06-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0011_auto_20200619_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pic1',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='car',
            name='pic2',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='car',
            name='pic3',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='car',
            name='pic4',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
        migrations.AddField(
            model_name='car',
            name='pic5',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
