# Generated by Django 3.0.1 on 2020-06-19 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0012_auto_20200619_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='pic1',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic2',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic4',
        ),
        migrations.RemoveField(
            model_name='car',
            name='pic5',
        ),
    ]
