# Generated by Django 3.0.1 on 2020-06-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0015_auto_20200619_0127'),
    ]

    operations = [
    ]
