# Generated by Django 3.0.1 on 2020-06-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0016_auto_20200619_0128'),
    ]

    operations = [
    ]
