# Generated by Django 3.0.1 on 2020-06-19 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0017_auto_20200619_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='pic1',
            field=models.ImageField(default=datetime.datetime(2020, 6, 19, 1, 32, 2, 740987, tzinfo=utc), upload_to='gallery'),
            preserve_default=False,
        ),
    ]
