# Generated by Django 3.0.1 on 2020-06-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0018_car_pic1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pic',
            field=models.ImageField(upload_to='gallery'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pic1',
            field=models.ImageField(default='gallery/error.png', null=True, upload_to='gallery'),
        ),
    ]
