# Generated by Django 3.0.1 on 2020-06-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0020_auto_20200619_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pic1',
            field=models.ImageField(default='non', null=True, upload_to='gallery'),
        ),
    ]
